import Mustache from 'mustache'
import widget from './widget.js'
import fs from 'fs'

function html(title, description, body) {
  return `<!doctype html>
  <html>
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="${description}">
      <meta name="about" content="Webpage generated by https://permanotes.app">
      <link href="https://cdn.jsdelivr.net/npm/daisyui@2.15.4/dist/full.css" rel="stylesheet" type="text/css" />
      <script src="https://cdn.tailwindcss.com/3.1.3"></script>  
      <script src="https://unpkg.com/arweave@1.11.4/bundles/web.bundle.min.js"></script>
    </head>
    <body>
      <main class="mt-16 prose-lg bg-base-100" style="margin-left: 32px; margin-right: 32px;">
      ${body}
      </main>
    </body>
  </html>  
`
}

function generate() {
  let body = Mustache.render(widget.template(), { address: 'vh-NTHVvlKZqRxc8LyyTNok65yQ55a_PJ1zWLb9G2JI' })
  body += widget.script()
  fs.writeFileSync('index.html', html('Hello', 'test', body))
}

generate()